"""Timing helpers for the two counting approaches shown in the prompt image."""

from dataclasses import dataclass
from html import escape
from pathlib import Path
from timeit import default_timer
from typing import Hashable, Sequence

from init_data import (
    data_module_path,
    load_initialized_array as load_initialized_array_data,
    read_arrays_module,
)


STUDENT_NICKNAME = ""

TASK_DIR = Path(__file__).resolve().parent
RESULTS_DIR = TASK_DIR / "results"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)


@dataclass(frozen=True)
class TimingResult:
    """Result of running one counting approach on a provided array."""

    counts: dict[Hashable, int]
    elapsed_seconds: float


@dataclass(frozen=True)
class PrefixEvaluation:
    """Timing results for both algorithms on several prefixes of one array."""

    prefix_lengths: list[int]
    count_method_times: list[float]
    dictionary_method_times: list[float]


def load_initialized_array(k: int) -> list[int]:
    """Load a reusable random array previously generated for this task."""

    return load_initialized_array_data(k, STUDENT_NICKNAME)


def load_initialized_arrays() -> dict[int, list[int]]:
    """Load all arrays generated by init_data.py for this task."""

    path = data_module_path(STUDENT_NICKNAME)
    arrays_by_k, _metadata_by_k = read_arrays_module(path)

    if not arrays_by_k:
        raise FileNotFoundError(f"No initialized arrays found in {path}")

    return arrays_by_k




def main() -> None:
    """Evaluate the generated arrays and save timing plots."""


if __name__ == "__main__":
    main()
